version: '3.8'
services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: darkpool_db
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: Deltuhdarkpools!7
      POSTGRES_DB: darkpool_data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data